# Generated by Django 6.0.7 on 2026-07-24 21:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('api_key', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('business', 'Business')], default='free', max_length=20)),
                ('calls_today', models.IntegerField(default=0)),
                ('reset_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
