# Generated by Django 6.0.7 on 2026-07-26 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_subscription', '0002_apicalllog_apicustomer_otpverification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('endpoint', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('count', models.IntegerField(default=1)),
            ],
            options={
                'unique_together': {('ip_address', 'endpoint', 'date')},
            },
        ),
    ]
