# Generated by Django 6.0.7 on 2026-08-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_subscription', '0004_apikey_apirequestlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='allowed_features',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
