# Generated by Django 6.0.7 on 2026-07-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventTypeWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50, unique=True)),
                ('rain_weight', models.FloatField(default=1.0)),
                ('wind_weight', models.FloatField(default=1.0)),
                ('heat_weight', models.FloatField(default=1.0)),
                ('humidity_weight', models.FloatField(default=1.0)),
            ],
        ),
    ]
