# Generated by Django 6.0.7 on 2026-08-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateproduct',
            name='image_url',
            field=models.URLField(blank=True, help_text="Amazon product image URL — 'Get Link' page se image right-click karke 'Copy Image Address' se milega"),
        ),
        migrations.AddField(
            model_name='affiliateproduct',
            name='price_display',
            field=models.CharField(blank=True, help_text="Optional — jaise '$24.99', sirf display ke liye", max_length=20),
        ),
    ]
