# Generated by Django 6.0.7 on 2026-08-02 15:03

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affiliates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('excerpt', models.CharField(max_length=300)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(help_text='Rich text content')),
                ('featured_image_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title tag — 50-60 chars ideal. Blank = post title use hoga', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description — 150-160 chars ideal. Blank = excerpt use hoga', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords, jaise: paris weather, europe travel, august trip', max_length=250)),
                ('affiliate_products', models.ManyToManyField(blank=True, to='affiliates.affiliateproduct')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogcategory')),
            ],
        ),
    ]
