# Generated by Django 6.0.7 on 2026-07-24 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('europe', 'Europe'), ('usa', 'USA'), ('other', 'Other')], default='other', max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('avg_temp_max', models.FloatField()),
                ('avg_temp_min', models.FloatField()),
                ('avg_rainfall', models.FloatField()),
                ('rainy_days', models.IntegerField()),
                ('sunshine_hours', models.FloatField()),
                ('avg_humidity', models.FloatField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_data', to='weather.city')),
            ],
            options={
                'unique_together': {('city', 'month')},
            },
        ),
    ]
