# Generated by Django 6.0.7 on 2026-07-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='historicalweather',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='historicalweather',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='historicalweather',
            unique_together={('city', 'year', 'month')},
        ),
    ]
