# Generated by Django 6.0.7 on 2026-07-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_historicalweather_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='has_hiking_trails',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='city',
            name='is_coastal',
            field=models.BooleanField(default=False),
        ),
    ]
