# Generated by Django 6.0.7 on 2026-08-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_city_has_hiking_trails_city_is_coastal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAPICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_type', models.CharField(choices=[('forecast', 'Live Forecast'), ('archive', 'Historical Archive'), ('geocoding', 'Geocoding')], max_length=20)),
                ('city_query', models.CharField(blank=True, max_length=100)),
                ('success', models.BooleanField(default=True)),
                ('status_code', models.IntegerField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='weather_ext_timesta_d710f3_idx'), models.Index(fields=['api_type', 'timestamp'], name='weather_ext_api_typ_a8b8a3_idx')],
            },
        ),
    ]
