# Generated by Django 6.0.7 on 2026-08-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_externalapicalllog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('weather', 'Weather'), ('trip_planner', 'Trip Planner'), ('event_risk', 'Event Risk'), ('other', 'Other')], max_length=20)),
                ('data_source', models.CharField(choices=[('cache', 'Cache (memory)'), ('database', 'Database'), ('external', 'Open-Meteo API')], max_length=20)),
                ('city_query', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='externalapicalllog',
            name='feature',
            field=models.CharField(choices=[('weather', 'Weather'), ('trip_planner', 'Trip Planner'), ('event_risk', 'Event Risk'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddIndex(
            model_name='externalapicalllog',
            index=models.Index(fields=['feature', 'timestamp'], name='weather_ext_feature_74a35f_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequestlog',
            index=models.Index(fields=['timestamp'], name='weather_ser_timesta_a7eb27_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequestlog',
            index=models.Index(fields=['feature', 'data_source', 'timestamp'], name='weather_ser_feature_417f50_idx'),
        ),
    ]
