# Generated by Django 6.0.7 on 2026-08-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_servicerequestlog_externalapicalllog_feature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
